name: Check ESLint on Pull Request

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: installing eslint
        run: npm i -g eslint
        with:
          node-version: '16'
      - name: Fixing Files
        run: eslint . --ext .ts,.js
